package ztime

import (
	"time"
)

// https://github.com/goodsign/monday/

func GetWeekDayName(langCode string, day time.Weekday) string {
	return WeekdayName[LangValue{langCode, int(day)}]
}

func GetMonthName(langCode string, month time.Month) string {
	return MonthName[LangValue{langCode, int(month)}]
}

var WeekdayName = map[LangValue]string{
	LangValue{"en", int(time.Sunday)}:    "Sunday",
	LangValue{"en", int(time.Monday)}:    "Monday",
	LangValue{"en", int(time.Tuesday)}:   "Tuesday",
	LangValue{"en", int(time.Wednesday)}: "Wednesday",
	LangValue{"en", int(time.Thursday)}:  "Thursday",
	LangValue{"en", int(time.Friday)}:    "Friday",
	LangValue{"en", int(time.Saturday)}:  "Saturday",

	LangValue{"no", int(time.Sunday)}:    "søndag",
	LangValue{"no", int(time.Monday)}:    "mandag",
	LangValue{"no", int(time.Tuesday)}:   "tirsdag",
	LangValue{"no", int(time.Wednesday)}: "onsdag",
	LangValue{"no", int(time.Thursday)}:  "torsdag",
	LangValue{"no", int(time.Friday)}:    "fredag",
	LangValue{"no", int(time.Saturday)}:  "lørdag",

	LangValue{"da", int(time.Sunday)}:    "søndag",
	LangValue{"da", int(time.Monday)}:    "mandag",
	LangValue{"da", int(time.Tuesday)}:   "tirsdag",
	LangValue{"da", int(time.Wednesday)}: "onsdag",
	LangValue{"da", int(time.Thursday)}:  "torsdag",
	LangValue{"da", int(time.Friday)}:    "fredag",
	LangValue{"da", int(time.Saturday)}:  "lørdag",

	LangValue{"de", int(time.Sunday)}:    "Sonntag",
	LangValue{"de", int(time.Monday)}:    "Montag",
	LangValue{"de", int(time.Tuesday)}:   "Dienstag",
	LangValue{"de", int(time.Wednesday)}: "Mittwoch",
	LangValue{"de", int(time.Thursday)}:  "Donnerstag",
	LangValue{"de", int(time.Friday)}:    "Friday",
	LangValue{"de", int(time.Saturday)}:  "Samstag",

	LangValue{"es", int(time.Sunday)}:    "domingo",
	LangValue{"es", int(time.Monday)}:    "lunes",
	LangValue{"es", int(time.Tuesday)}:   "martes",
	LangValue{"es", int(time.Wednesday)}: "miércoles",
	LangValue{"es", int(time.Thursday)}:  "jueves",
	LangValue{"es", int(time.Saturday)}:  "viernes",
	LangValue{"es", int(time.Friday)}:    "sábado",

	LangValue{"fi", int(time.Sunday)}:    "sunnuntai",
	LangValue{"fi", int(time.Monday)}:    "maanantai",
	LangValue{"fi", int(time.Tuesday)}:   "tiistai",
	LangValue{"fi", int(time.Wednesday)}: "keskiviikko",
	LangValue{"fi", int(time.Thursday)}:  "torstai",
	LangValue{"fi", int(time.Friday)}:    "perjantai",
	LangValue{"fi", int(time.Saturday)}:  "lauantai",

	LangValue{"fr", int(time.Sunday)}:    "dimanche",
	LangValue{"fr", int(time.Monday)}:    "lundi",
	LangValue{"fr", int(time.Tuesday)}:   "mardi",
	LangValue{"fr", int(time.Wednesday)}: "mercredi",
	LangValue{"fr", int(time.Thursday)}:  "jeudi",
	LangValue{"fr", int(time.Friday)}:    "vendredi",
	LangValue{"fr", int(time.Saturday)}:  "samedi",

	LangValue{"it", int(time.Sunday)}:    "domenica",
	LangValue{"it", int(time.Monday)}:    "lunedì",
	LangValue{"it", int(time.Tuesday)}:   "martedì",
	LangValue{"it", int(time.Wednesday)}: "mercoledì",
	LangValue{"it", int(time.Thursday)}:  "giovedì",
	LangValue{"it", int(time.Friday)}:    "venerdì",
	LangValue{"it", int(time.Saturday)}:  "sabato",

	LangValue{"pl", int(time.Sunday)}:    "domingo",
	LangValue{"pl", int(time.Monday)}:    "segunda-feira",
	LangValue{"pl", int(time.Tuesday)}:   "terça-feira",
	LangValue{"pl", int(time.Wednesday)}: "quarta-feira",
	LangValue{"pl", int(time.Thursday)}:  "quinta-feira",
	LangValue{"pl", int(time.Friday)}:    "sexta-feira",
	LangValue{"pl", int(time.Saturday)}:  "sábado",

	LangValue{"zhHK", int(time.Sunday)}:    "星期日",
	LangValue{"zhHK", int(time.Monday)}:    "星期一",
	LangValue{"zhHK", int(time.Tuesday)}:   "星期二",
	LangValue{"zhHK", int(time.Wednesday)}: "星期三",
	LangValue{"zhHK", int(time.Thursday)}:  "星期四",
	LangValue{"zhHK", int(time.Friday)}:    "星期五",
	LangValue{"zhHK", int(time.Saturday)}:  "星期六",

	LangValue{"sv", int(time.Sunday)}:    "söndag",
	LangValue{"sv", int(time.Monday)}:    "måndag",
	LangValue{"sv", int(time.Tuesday)}:   "tisdag",
	LangValue{"sv", int(time.Wednesday)}: "onsdag",
	LangValue{"sv", int(time.Thursday)}:  "torsdag",
	LangValue{"sv", int(time.Friday)}:    "fredag",
	LangValue{"sv", int(time.Saturday)}:  "lördag",

	LangValue{"tr", int(time.Sunday)}:    "Pazar",
	LangValue{"tr", int(time.Monday)}:    "Pazartesi",
	LangValue{"tr", int(time.Tuesday)}:   "Salı",
	LangValue{"tr", int(time.Wednesday)}: "Çarşamba",
	LangValue{"tr", int(time.Thursday)}:  "Perşembe",
	LangValue{"tr", int(time.Friday)}:    "Cuma",
	LangValue{"tr", int(time.Saturday)}:  "Cumartesi",
}

var MonthName = map[LangValue]string{
	LangValue{"en", int(time.January)}:   "January",
	LangValue{"en", int(time.February)}:  "February",
	LangValue{"en", int(time.March)}:     "March",
	LangValue{"en", int(time.April)}:     "April",
	LangValue{"en", int(time.May)}:       "May",
	LangValue{"en", int(time.June)}:      "June",
	LangValue{"en", int(time.July)}:      "July",
	LangValue{"en", int(time.August)}:    "August",
	LangValue{"en", int(time.September)}: "September",
	LangValue{"en", int(time.October)}:   "October",
	LangValue{"en", int(time.November)}:  "November",
	LangValue{"en", int(time.December)}:  "December",

	LangValue{"no", int(time.January)}:   "januar",
	LangValue{"no", int(time.February)}:  "februar",
	LangValue{"no", int(time.March)}:     "mars",
	LangValue{"no", int(time.April)}:     "april",
	LangValue{"no", int(time.May)}:       "mai",
	LangValue{"no", int(time.June)}:      "juni",
	LangValue{"no", int(time.July)}:      "juli",
	LangValue{"no", int(time.August)}:    "august",
	LangValue{"no", int(time.September)}: "september",
	LangValue{"no", int(time.October)}:   "oktober",
	LangValue{"no", int(time.November)}:  "november",
	LangValue{"no", int(time.December)}:  "desember",

	LangValue{"da", int(time.January)}:   "januar",
	LangValue{"da", int(time.February)}:  "february",
	LangValue{"da", int(time.March)}:     "marts",
	LangValue{"da", int(time.April)}:     "april",
	LangValue{"da", int(time.May)}:       "maj",
	LangValue{"da", int(time.June)}:      "juni",
	LangValue{"da", int(time.July)}:      "juli",
	LangValue{"da", int(time.August)}:    "august",
	LangValue{"da", int(time.September)}: "september",
	LangValue{"da", int(time.October)}:   "oktober",
	LangValue{"da", int(time.November)}:  "november",
	LangValue{"da", int(time.December)}:  "december",

	LangValue{"de", int(time.January)}:   "Januar",
	LangValue{"de", int(time.February)}:  "Februar",
	LangValue{"de", int(time.March)}:     "März",
	LangValue{"de", int(time.April)}:     "April",
	LangValue{"de", int(time.May)}:       "Mai",
	LangValue{"de", int(time.June)}:      "Juni",
	LangValue{"de", int(time.July)}:      "Juli",
	LangValue{"de", int(time.August)}:    "August",
	LangValue{"de", int(time.September)}: "September",
	LangValue{"de", int(time.October)}:   "Oktober",
	LangValue{"de", int(time.November)}:  "November",
	LangValue{"de", int(time.December)}:  "Dezember",

	LangValue{"es", int(time.January)}:   "enero",
	LangValue{"es", int(time.February)}:  "febrero",
	LangValue{"es", int(time.March)}:     "marzo",
	LangValue{"es", int(time.April)}:     "abril",
	LangValue{"es", int(time.May)}:       "mayo",
	LangValue{"es", int(time.June)}:      "junio",
	LangValue{"es", int(time.July)}:      "julio",
	LangValue{"es", int(time.August)}:    "agosto",
	LangValue{"es", int(time.September)}: "septiembre",
	LangValue{"es", int(time.October)}:   "octubre",
	LangValue{"es", int(time.November)}:  "noviembre",
	LangValue{"es", int(time.December)}:  "diciembre",

	LangValue{"fi", int(time.January)}:   "tammikuuta",
	LangValue{"fi", int(time.February)}:  "helmikuuta",
	LangValue{"fi", int(time.March)}:     "maaliskuuta",
	LangValue{"fi", int(time.April)}:     "huhtikuuta",
	LangValue{"fi", int(time.May)}:       "toukokuuta",
	LangValue{"fi", int(time.June)}:      "kesäkuuta",
	LangValue{"fi", int(time.July)}:      "heinäkuuta",
	LangValue{"fi", int(time.August)}:    "elokuuta",
	LangValue{"fi", int(time.September)}: "syyskuuta",
	LangValue{"fi", int(time.October)}:   "lokakuuta",
	LangValue{"fi", int(time.November)}:  "marraskuuta",
	LangValue{"fi", int(time.December)}:  "joulukuuta",

	LangValue{"it", int(time.January)}:   "gennaio",
	LangValue{"it", int(time.February)}:  "febbraio",
	LangValue{"it", int(time.March)}:     "marzo",
	LangValue{"it", int(time.April)}:     "aprile",
	LangValue{"it", int(time.May)}:       "maggio",
	LangValue{"it", int(time.June)}:      "giugno",
	LangValue{"it", int(time.July)}:      "luglio",
	LangValue{"it", int(time.August)}:    "agosto",
	LangValue{"it", int(time.September)}: "settembre",
	LangValue{"it", int(time.October)}:   "ottobre",
	LangValue{"it", int(time.November)}:  "novembre",
	LangValue{"it", int(time.December)}:  "dicembre",

	LangValue{"pl", int(time.January)}:   "janeiro",
	LangValue{"pl", int(time.February)}:  "fevereiro",
	LangValue{"pl", int(time.March)}:     "março",
	LangValue{"pl", int(time.April)}:     "abril",
	LangValue{"pl", int(time.May)}:       "maio",
	LangValue{"pl", int(time.June)}:      "junho",
	LangValue{"pl", int(time.July)}:      "julho",
	LangValue{"pl", int(time.August)}:    "agosto",
	LangValue{"pl", int(time.September)}: "setembro",
	LangValue{"pl", int(time.October)}:   "outubro",
	LangValue{"pl", int(time.November)}:  "novembro",
	LangValue{"pl", int(time.December)}:  "dezembro",

	LangValue{"zhHK", int(time.January)}:   "1 月",
	LangValue{"zhHK", int(time.February)}:  "2 月",
	LangValue{"zhHK", int(time.March)}:     "3 月",
	LangValue{"zhHK", int(time.April)}:     "4 月",
	LangValue{"zhHK", int(time.May)}:       "5 月",
	LangValue{"zhHK", int(time.June)}:      "6 月",
	LangValue{"zhHK", int(time.July)}:      "7 月",
	LangValue{"zhHK", int(time.August)}:    "8 月",
	LangValue{"zhHK", int(time.September)}: "9 月",
	LangValue{"zhHK", int(time.October)}:   "10 月",
	LangValue{"zhHK", int(time.November)}:  "11 月",
	LangValue{"zhHK", int(time.December)}:  "12 月",

	LangValue{"sv", int(time.January)}:   "januari",
	LangValue{"sv", int(time.February)}:  "februari",
	LangValue{"sv", int(time.March)}:     "mars",
	LangValue{"sv", int(time.April)}:     "april",
	LangValue{"sv", int(time.May)}:       "maj",
	LangValue{"sv", int(time.June)}:      "juni",
	LangValue{"sv", int(time.July)}:      "juli",
	LangValue{"sv", int(time.August)}:    "augusti",
	LangValue{"sv", int(time.September)}: "september",
	LangValue{"sv", int(time.October)}:   "oktober",
	LangValue{"sv", int(time.November)}:  "november",
	LangValue{"sv", int(time.December)}:  "december",

	LangValue{"tr", int(time.January)}:   "Ocak",
	LangValue{"tr", int(time.February)}:  "Şubat",
	LangValue{"tr", int(time.March)}:     "Mart",
	LangValue{"tr", int(time.April)}:     "Nisan",
	LangValue{"tr", int(time.May)}:       "Mayıs",
	LangValue{"tr", int(time.June)}:      "Haziran",
	LangValue{"tr", int(time.July)}:      "Temmuz",
	LangValue{"tr", int(time.August)}:    "Ağustos",
	LangValue{"tr", int(time.September)}: "Eylül",
	LangValue{"tr", int(time.October)}:   "Ekim",
	LangValue{"tr", int(time.November)}:  "Kasım",
	LangValue{"tr", int(time.December)}:  "Aralık",
}
